### PR TITLE
cmd/lab_todo: Finalized lab todo issue, updated go-gitlab

### PR DESCRIPTION
**Pull request by zampierilucas**
Added missing link between go-gitlab and lab todo issue to make it
functional.

Signed-off-by: Lucas Zampieri <lzampier@redhat.com>

### CODE REVIEW

**Review by bmeneguele — APPROVED** [review]
Ah, I thought that @prarit had added it during his TODO improvement PRs :)
Many thanks.

**Comment by prarit** [comment]
Haha :)  I was the one who realized it wasn't supported!

**Comment by bmeneguele** [comment]
> Haha :) I was the one who realized it wasn't supported!

Ah no., I remember that, I just thought you added the full support later :D.

**Comment by bmeneguele** [comment]
@zampierilucas it seems the build failed due to some golint suggestion.

**Comment by bmeneguele** [comment]
@zampierilucas would you mind squashing the "Added EOF" patch to the first one?
I think the additional patch is really a "no-op" and would be better to have the change added to the first patch instead.

**Comment by bmeneguele** [comment]
Thanks @zampierilucas

**Pull request merged**
