### PR TITLE
Open the current merge request with lab mr b

### PR DESCRIPTION
**Pull request by MartinDelille**
This is a work in progress.

The current code fails with the following error:

```
../../go/src/github.com/zaquestion/lab/cmd/mr_browse.go:46:17: unknown field 'SourceBranch' in struct literal of type "github.com/zaquestion/lab/vendor/github.com/xanzy/go-gitlab".ListProjectMergeRequestsOptions
```

There is indeed a `ListProjectMergeRequestsOptions.SourceBranch` here: https://github.com/xanzy/go-gitlab/blob/master/merge_requests.go#L262

Unfortunately, I have a different file in `vi vendor/github.com/xanzy/go-gitlab/merge_requests.go`...

### CODE REVIEW

**Comment by MartinDelille** [comment]
Ok I fixed the problems I had but now travis failed. I guess I should update the tests. 

@zaquestion How can I run the test locally?

**Comment by MartinDelille** [comment]
Ok it fails locally:

```
$ make test
bash -c "trap 'trap - SIGINT SIGTERM ERR; mv testdata/.git testdata/test.git; rm coverage-* 2>&1 > /dev/null; exit 1' SIGINT SIGTERM ERR; /Applications/Xcode.app/Contents/Developer/usr/bin/make internal-test"
rm coverage-* 2>&1 > /dev/null || true
rm: coverage-*: No such file or directory
mv testdata/test.git testdata/.git
go test -coverprofile=coverage-main.out -covermode=count -coverpkg ./... -run= github.com/zaquestion/lab/cmd github.com/zaquestion/lab/internal/...
The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? The authenticity of host 'gitlab.com (35.231.145.151)' can't be established.
ECDSA key fingerprint is SHA256:HbW3g8zUjNSksFbqTiUWPWg2Bq1x8xdGUrliXFzSnUw.
Are you sure you want to continue connecting (yes/no)? ^C--- FAIL: Test_mrCmd (1.59s)
	root_test.go:72: ../testdata-2243430853747698137
    --- FAIL: Test_mrCmd/create (1.55s)
    	mr_test.go:34: POST https://gitlab.com/api/v4/projects/5694926/merge_requests: 409 {message: [Cannot Create: This merge request already exists: ["mr title"]]}
    		/diffs
    		PASS
    		coverage: 13.8% of statements in ./...

        Error Trace:    mr_test.go:35
    	Error:      	"POST https://gitlab.com/api/v4/projects/5694926/merge_requests: 409 {message: [Cannot Create: This merge request already exists: ["mr title"]]}
    	            	/diffs
    	            	PASS
    	            	coverage: 13.8% of statements in ./...
    	            	" does not contain "https://gitlab.com/lab-testing/test/merge_requests"
    	Test:       	Test_mrCmd/create
--- FAIL: Test_projectCreateCmd (1.01s)
	root_test.go:72: ../testdata-4018908385734095056
    --- FAIL: Test_projectCreateCmd/create (0.82s)
    	project_create_test.go:31: 2018/09/23 06:08:01 project_create.go:48: POST https://gitlab.com/api/v4/projects: 400 {message: {base: [PG::NotNullViolation: ERROR:  null value in column "approvals_before_merge" violates not-null constraint
    		DETAIL:  Failing row contains (8514392, testdata-4018908385734095056, testdata-4018908385734095056, , 2018-09-23 04:08:01.041227+00, 2018-09-23 04:08:01.041227+00, 1636476, 2002378, null, null, 10, f, null, null, 0, f, null, null, null, null, t, f, null, f, null, null, null, null, null, t, xji2xdxx7PukEsRxYrPo, null, t, 3600, f, t, f, null, null, t, f, null, nfs-file22, f, null, null, null, , f, null, t, t, 1, null, 11, null, null, null, null, null, f, null, t, null, null, null, null, null, t, t, null).
    		: INSERT INTO "projects" ("name", "path", "description", "visibility_level", "approvals_before_merge", "namespace_id", "creator_id", "runners_token", "created_at", "updated_at", "description_html", "cached_markdown_version", "packages_enabled", "archived", "resolve_outdated_diff_discussions", "container_registry_enabled", "repository_storage", "shared_runners_enabled", "only_allow_merge_if_all_discussions_are_resolved", "only_mirror_protected_branches") VALUES ('testdata-4018908385734095056', 'testdata-4018908385734095056', '', 10, NULL, 2002378, 1636476, 'xji2xdxx7PukEsRxYrPo', '2018-09-23 04:08:01.041227', '2018-09-23 04:08:01.041227', '', 11, 't', 'f', 'f', 't', 'nfs-file22', 't', 'f', 't') RETURNING "id"]}, {limit_reached: []}}

    	project_create_test.go:32: exit status 1
	project_create_test.go:50: failed to find project for cleanup: gitlab project not found
FAIL	github.com/zaquestion/lab/cmd	32.091s
?   	github.com/zaquestion/lab/internal/browser	[no test files]
ok  	github.com/zaquestion/lab/internal/config	0.025s	coverage: 6.6% of statements in ./...
make[1]: *** [internal-test] Error 1
make: *** [test] Error 1
```

**Comment by zaquestion** [comment]
Yeah the tests can be a bit annoying because they test against the real gitlab.com

You should just need to have an ssh key connected to a user on gitlab. Sorry there aren't better instructions on running the tests. You can select tests with 
```
make test run=Test create
```

**Comment by MartinDelille** [comment]
> You should just need to have an ssh key connected to a user on gitlab. 

I had one but I forgot that I changed my laptop since!

The problem now is that I don't have the right to create a merge request on this project.

The problem on travis is that there is an open merge request on the project with the same title: https://travis-ci.org/zaquestion/lab/builds/432038074#L576

I will try to close it via travis.

**Comment by MartinDelille** [comment]
@zaquestion Maybe it'll be easier if you close it by hand!

**Comment by zaquestion** [comment]
Thats a pretty weird error -- I suspect it might be reproducible on master as well and have nothing to do with your code

**Comment by zaquestion** [comment]
Do you think you can add a test using https://github.com/zaquestion/lab/blob/master/cmd/mr_browse_test.go as guidance

**Comment by zaquestion** [comment]
@MartinDelille The test issue should be fixed by #222 -- can you rebase/update your branch. Sorry for the merge conflict!

**Comment by MartinDelille** [comment]
It fixed the problem!
I will try to add a test now that the build pass because I don't want to drop the code coverage! 😉

**Comment by MartinDelille** [comment]
Do you have a test scenario to propose? I'm a kind of lost how to do that.

**Comment by zaquestion** [comment]
@MartinDelille Sorry I just started a new job and haven't had much time to help out here. I'd suggest something like the existing test in https://github.com/zaquestion/lab/blob/master/cmd/mr_browse_test.go but don't pass an MR. You may have to checkout the mr test branch as well ( https://github.com/zaquestion/lab/blob/master/cmd/mr_test.go#L17-L23 )

```
func Test_mrBrowse(t *testing.T) {
	oldBrowse := browse
	defer func() { browse = oldBrowse }()

	browse = func(url string) error {
		require.Equal(t, "https://gitlab.com/zaquestion/test/merge_requests/<not sure what this would be>", url)
		return nil
	}

	mrBrowseCmd.Run(nil, []string{})
}
```

**Comment by MartinDelille** [comment]
Hi @zaquestion !

It works on my side locally. I tried again to write test but it requires times that I don't have. Maybe you could merge it without test so that people can at least use the feature?

We'll create an issue to create a test for this feature then (I don't like untested code too but sometimes we need to get thing done).

**Pull request merged**
