### PR TITLE
mr_reopen: add command for reopening a closed MR

### PR DESCRIPTION
**Pull request by bmeneguele**
Add `lab mr reopen` command.

### CODE REVIEW

**Comment by prarit** [comment]
I like this, but would creating the files as mr_open.go and mr_open_test.go, instead of mr_reopen.go and mr_reopen_test.go be better?  You could add a command alias for 'reopen'.  It would then balance nicely with the mr_close files.

**Comment by prarit** [comment]
@bmeneguele I've taken your latest MR test fix and am going to add it separately in #523 .  FYI.

**Comment by bmeneguele** [comment]
> I like this, but would creating the files as mr_open.go and mr_open_test.go, instead of mr_reopen.go and mr_reopen_test.go be better? You could add a command alias for 'reopen'. It would then balance nicely with the mr_close files.

Hmmm, that's an option indeed. However, won't it create a "confusion" between `lab mr create` and `lab mr open` ? Although they do completely different things, the words are quite close to their meaning. OTOH `reopen` has a clear and obvious behavior: it won't create nor open anything, it'll only reopen a closed MR.

**Comment by prarit** [comment]
> > I like this, but would creating the files as mr_open.go and mr_open_test.go, instead of mr_reopen.go and mr_reopen_test.go be better? You could add a command alias for 'reopen'. It would then balance nicely with the mr_close files.
> 
> Hmmm, that's an option indeed. However, won't it create a "confusion" between `lab mr create` and `lab mr open` ? Although they do completely different things, the words are quite close to their meaning. OTOH `reopen` has a clear and obvious behavior: it won't create nor open anything, it'll only reopen a closed MR.

That's a good counter point :).  There's no good answer here.  Stick with "reopen" ;)

**Review by prarit — APPROVED** [review]

**Pull request merged**
