### PR TITLE
Add support for posting notes to Merge Requests.

### PR DESCRIPTION
**Pull request by rvtraveller**
Note that this only supports notes and not discussions. There is a lofty set of ideal criteria for this in #83 including the ability to have flags for line numbers. This doesn't support that, but I think this provides a good starting point and additional flags can be added in subsequent feature requests.

`lab mr note <mr_id> -m <message>`

I wrote a test...but I'm not positive how well it is going to work. I largely mirrored the issue note test. I have run this manually and it does work so hopefully the test matches that.

### CODE REVIEW

**Comment by ataylorme** [comment]
@zaquestion can you tag a new release of lab? @rvtraveller and I are wanting to work on getting lab support in [composer lock updater](https://github.com/danielbachhuber/composer-lock-updater), which currently supports GiHub hub, so that we can have our projects on GitLab updated more easily.

A tagged release is preferred to building lab from master.

**Comment by zaquestion** [comment]
Yeah of course, I'll cut a tag tomorrow when I've got a chance to watch the build

**Comment by zaquestion** [comment]
@ataylorme done

**Comment by ataylorme** [comment]
Great, thank you!

**Pull request merged**
