### PR TITLE
Add reviewers

### PR DESCRIPTION
**Pull request by prarit**
Add an option to add and remove reviewers from 'mr edit' and 'mr create'.  This involves generalizing and moving some code around.  I've also added the ability to add and remove reviewers and assignees via user's email addresses.

Closes: #639 

Signed-off-by: Prarit Bhargava <prarit@redhat.com>

### CODE REVIEW

**Review by bmeneguele — APPROVED** [review]
Yep, the code LGTM!

**Comment by prarit** [comment]
I'll figure out the failures this morning.  I also have to add testing for the options.

**Comment by bmeneguele** [comment]
The only issue is a `gofmt` one:
```diff
  func getUserID(user string) *int {
 	var (
-		err error
+		err    error
 		userID int
 	)
 ```

The MR I removed manually.
About the testing.. that's true., but is it possible to add the MR author as a reviewer? Otherwise, it can be annoying to add someone real there :). Maybe testing the only the `getUserID`.

**Comment by prarit** [comment]
I will push testing for these commands in another PR.

**Comment by bmeneguele** [comment]
@AlexanderVanEck we're planning to make a release pretty soon. We were facing some issues in the past weeks with our CI/CD and weren't able to officially release a new version. But things are now working again :-)

**Comment by AlexanderVanEck** [comment]
Thanks Bruno! Great to hear :) looking forward to it.

**Comment by AlexanderVanEck** [comment]
Awesome! Thank you :) Will install tomorrow.

Met vriendelijke groeten / With kind regards,

*Alexander van Eck*
Owner X-All

Mobile: *+31 (0)6 532 46 146* | ***@***.*** ***@***.***>*

**Comment by AlexanderVanEck** [comment]
Works @bmeneguele. Wonderful 🙌  Thank you.

**Pull request merged**
