### PR TITLE
mr_show: fix line wrapping

### LINKED ISSUE #632: "lab mr show" output with PAGER=most is unreadable, readable but mangled with PAGER=less
```
With PAGER=most:

!4 af_unix: fix struct pid memory leak
===================================

^[[38;5;252m^[[38;5;252m  ^[[38;5;252mFrom: Eric Dumazet ^[[38;5;35;1medumazet@google.com^[[38;5;252m ^[[38;5;30;4mmailto:edumazet@google.com^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[3$
  ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m $
^[[38;5;252m^[[38;5;252m  ^[[38;5;252mBugzilla: ^[[38;5;30;4mhttps://bugzilla.redhat.com/show_bug.cgi?id=1901744^[[38;5;252m ^[[38;5;252mUpstream^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m $
^[[38;5;252m  ^[[38;5;252mStatus:^[[38;5;252m linux.git ^[[38;5;252mBuild Info:^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^$
^[[38;5;30;4m^[[38;5;30;4m  ^[[38;5;30;4mhttps://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33290816^[[38;5;252m ^[[38;5;252mTested:
^[[38;5;252m  ^[[38;5;252mreproducer in^[[38;5;252m bugzilla^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5$
  ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m $
^[[38;5;252m^[[38;5;252m  ^[[38;5;252mContext differences, due to upstream commit 7cc05662682d (net: remove^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m
^[[38;5;252m  ^[[38;5;252msock_^[[38;5;252miocb) not having been backported to^[[38;5;252m RHEL-7.^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;252m ^[[38;5;$
....rest snipped...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

With PAGER=less (or with PAGER unset, "less" is the default pager):

!4 af_unix: fix struct pid memory leak
===================================

  From: Eric Dumazet edumazet@google.com mailto:edumazet@google.com           
                                                                              
  Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1901744 Upstream      
  Status: linux.git Build Info:                                               
  https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33290816 Tested:
  reproducer in bugzilla                                                      
                                                                              
  Context differences, due to upstream commit 7cc05662682d (net: remove       
  sock_iocb) not having been backported to RHEL-7.
...
^^^^^^^^^^^^^^

This looks marginally better (I actually can read it), but lines are
incorrectly wrapped, and the paging action does not actually happen -
after output, I end up in shell prompt, not in "less", so the intent
of letting me scroll over a large output is not achieved.

Only the forced "do not try to paginate" approach, like
"lab mr show N | cat" gives the right output - note that
lines are now CORRECTLY wrapped, for example "Upstream Status"
line does not attach itself to the tail of BZ url on previous
line):

!4 af_unix: fix struct pid memory leak
===================================
From: Eric Dumazet <edumazet@google.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1901744
Upstream Status: linux.git
Build Info: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=33290816
Tested: reproducer in bugzilla

Context differences, due to upstream commit 7cc05662682d (net: remove sock_iocb) not having been backported to RHEL-7.
...
```

### PR DESCRIPTION
**Pull request by bmeneguele**
This PR fixes two issues: 
1. the line wrapping behavior that `glamour` lib has enabled by default at the mark of 80 columns, which I think shouldn't, since the user is expecting to see what was exactly sent;
2. use only 16 ANSI colors pallet to allow more simple terminals and pagers to work properly.

If item 2 isn't desirable, I'm fine with dropping it.
Fixes #632.

### CODE REVIEW

**Comment by bmeneguele** [comment]
This MR fixes #632 wrt the rendering result being different from what can be seen in both commit log and webui rendering.

**Comment by bmeneguele** [comment]
This new PR version also bring the change to the color scheme used for `lab` output.
But if the second patch is not-desirable, that's fine by me.
This PR fully fixes #632 now.

**Review by prarit — APPROVED** [review]
Is that all it was?  That's awesome :)  It works so well in testing.

LGTM

**Comment by dvlasenk** [comment]
Still sometimes emits 8-bit color escapes, which are not understood by e.g. "most".
Try "PAGER=most lab mr show 177" in rhel-8 tree:

!177 CNB: bitfield: add FIELD_MAX() and field_max()
===================================

  Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1939478
  Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=35467574
  Tested: Just build

^[[38;5;251m    ^[[38;5;251mcommit e31a50162feb352147d3fc87b9e036703c8f2636
    ^[[38;5;251mAuthor: Alex Elder <elder@linaro.org>
    ^[[38;5;251mDate:   Thu Mar 12 11:44:27 2020 -0500
    ^[[38;5;251m
    ^[[38;5;251m    bitfield.h: add FIELD_MAX() and field_max()
...

**Comment by bmeneguele** [comment]
Wow.. that's unexpected!
I'm going to check it further and see why it's partially applying the extended ANSI there.
It seems to be related to the "indentation".
Thanks once again for catching the issue @dvlasenk :)

**Pull request merged**
