### PR TITLE
Issue, MR filtering by labels and state

### PR DESCRIPTION
**Pull request by nkprince007**

### CODE REVIEW

**Comment by nkprince007** [comment]
@zaquestion need some help with tests here.

**Comment by nkprince007** [comment]
pending docs? @zaquestion

**Comment by zaquestion** [comment]
Typically I've been creating those at release time. They get auto generated. You _should_ be able to merge this

**Comment by nkprince007** [comment]
I have no merge access :(

**Comment by zaquestion** [comment]
Interesting, sorry about that! I though thats how this "approval" thing worked. heh, I've even been sitting here googling it trying to be sure, but the docs have been so so.

**Pull request merged**
