### PR TITLE
(ci status) support a short text based pipeline/job status

### PR DESCRIPTION
**Pull request by zaquestion**
To address #261 & through the use of `--wait` hopefully #240

### CODE REVIEW

**Comment by zaquestion** [comment]
@claytonrcarter @nkprince007 @MartinDelille  need to actually add some tests, but what are your thoughts on this?

Example output
```
unittest: unittest - success
build: docker - success
sandbox: deploy_s-s0 - success
sandbox: deploy_s-s1 - manual

Pipeline Status: success
```

**Comment by nkprince007** [comment]
> @claytonrcarter @nkprince007 @MartinDelille need to actually add some tests, but what are your thoughts on this?
> 
> Example output
> 
> ```
> unittest: unittest - success
> build: docker - success
> sandbox: deploy_s-s0 - success
> sandbox: deploy_s-s1 - manual
> 
> Pipeline Status: success
> ```

Looks good, but I'd prefer having them aligned properly.

Like so:
```
unittest: unittest - success
build:    docker - success
sandbox:  deploy_s-s0 - success
sandbox:  deploy_s-s1 - manual

Pipeline Status: success
```

Reference: https://golang.org/pkg/text/tabwriter/

**Comment by claytonrcarter** [comment]
I agree with @nkprince007 about aligning the job names. That said, I don't think such a small tweak should hold this up. It's simple, clean and works! A followup PR would to change the alignment would be easy enough.

Do you have any ideas about how to test it?

**Comment by zaquestion** [comment]
Yeah easy to test just need to actually do it. Should be able to get the in this weekend.

**Comment by zaquestion** [comment]
@nkprince007 @claytonrcarter I've added some tests and aligned the text with `text/tabwriter`

**Comment by claytonrcarter** [comment]
Love it!

**Pull request merged**
