### PR TITLE
create a repository in a group

### PR DESCRIPTION
**Pull request by kovetskiy**
this feature allows specifying namespace name while creating a repository

### CODE REVIEW

**Comment by claytonrcarter** [comment]
Thanks! This is glorious, and so simple! Works as expected and a long overdue addition. I believe that this could close #211, too.

Although I think this would be fine to merge as is, I do have a couple of nitpicky things:
1. The "Long" comment on line 21 of `project_create` can be updated to remove "in your user namespace"
2. I would love to see a comment clarifying that leaving `namespaceID` unassigned will default to the users current namespace. Maybe it's just me, but I had to double check that I wasn't missing something that looked up my namespace if `-g` wasn't used. (FWIW, `NamespaceID` is flagged with `omitempty` in [`CreateProjectOptions`](https://godoc.org/github.com/xanzy/go-gitlab#CreateProjectOptions))

But again, this is great! Thanks again!

**Comment by kovetskiy** [comment]
1. There is no comment on 21 line of `project_create`, I'm not sure what you have pointed to, please comment it in the review tab, it will be much more convenient.
2. Will add.

**Comment by kovetskiy** [comment]
Here you go, feel free to squash the commits

**Comment by claytonrcarter** [comment]
Thank you, @kovetskiy!

@zaquestion I can't merge because it looks like Travis is stuck, but this looks like it's good to go and ready for merge.

**Comment by kovetskiy** [comment]
@claytonrcarter any chance to merge the PR?

**Comment by kovetskiy** [comment]
ping @za
@claytonrcarter

**Comment by claytonrcarter** [comment]
Sorry for the delay; there is a high chance of merging the PR, but my hands are currently tied. I don't have perm to merge if CI is stuck or doesn't pass, and that's where we are. We'll get it in, though; don't worry, but please be patient. Thanks for understanding.

**Comment by kovetskiy** [comment]
@zaquestion ping

**Comment by kovetskiy** [comment]
@claytonrcarter 
Hi, I'm closing this PR because I need to implement more features to work with GitLab more effectively. 

I'll be glad to merge new features back to upstream when maintainers of lab come back, but for now, I'm going to maintain my own fork. Thanks.

**Pull request closed without merging**
