### PR TITLE
lab: update go.mod version

### PR DESCRIPTION
**Pull request by tydavis**
Update go.mod version to take advantage of the latest module graph and
lazy-loading mechanisms in 1.17+

https://go.dev/doc/modules/gomod-ref#go-notes

### CODE REVIEW

**Comment by bmeneg** [comment]
Could you also update the go version used in both .gitlab-ci.yml and .travis.yml files? So we can have the tests running against the same version. (yes, they were already mismatching 🤦 )

**Comment by bmeneg** [comment]
Oh, ok, Go 1.17 brought new build directives, finally.
Even though I have to rework this specific syscalls (use a better package) could you add the new `//go:build` directives as pointed out by the `gofmt` test output? But leave the old `// +build` ones as is, so people running older Go versions can still build it.

```diff
@@ -0,0 +1,26 @@
+diff -u cmd/root_nowindows_test.go.orig cmd/root_nowindows_test.go
+--- cmd/root_nowindows_test.go.orig	2022-01-06 18:11:49.896838864 +0000
++++ cmd/root_nowindows_test.go	2022-01-06 18:11:49.896838864 +0000
+@@ -1,3 +1,4 @@
++//go:build !windows
+ // +build !windows
+ 
+ package cmd
+diff -u cmd/root_windows_test.go.orig cmd/root_windows_test.go
+--- cmd/root_windows_test.go.orig	2022-01-06 18:11:49.896838864 +0000
++++ cmd/root_windows_test.go	2022-01-06 18:11:49.896838864 +0000
+@@ -1,3 +1,4 @@
++//go:build windows
+ // +build windows
+ 
+ package cmd
+diff -u cmd/util_bsd.go.orig cmd/util_bsd.go
+--- cmd/util_bsd.go.orig	2022-01-06 18:11:49.904842865 +0000
++++ cmd/util_bsd.go	2022-01-06 18:11:49.908844864 +0000
+@@ -1,5 +1,6 @@
+ // This file contains Darwin (MacOS) and *BSD specific calls.
+ 
++//go:build freebsd || openbsd || dragonfly || darwin
+ // +build freebsd openbsd dragonfly darwin
+ 
+ package cmd
The command "diff -u <(echo -n) <(gofmt -d .)" exited with 1.
```

It's

**Comment by tydavis** [comment]
@bmeneg Build directives are updated.

**Comment by bmeneg** [comment]
@tydavis, the `util_darwin.go` that you created isn't necessary. We kept `darwin` in the `util_bsd.go` build directive exactly because they're are identical, avoiding one additional file. In this space, darwin is mostly a mimic of freebsd's kernel, and keeping the directive for other BSDs is also important: few months ago I was using OpenBSD at home and used lab eventually and I might be the only one. DrangonflyBSD might be less used, but it doesn't hurt on keeping it there in the _bsd file.

**Comment by tydavis** [comment]
@bmeneg something went wrong with my autosave formatters. I've fixed it.

**Review by bmeneg — APPROVED** [review]
Seems fine now :D
Many thanks @tydavis !

**Pull request merged**
